using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;
using System.Linq;

public class GameManager : MonoBehaviourPun
{
    [Header("Players")]
    public string playerPrefabPath;
    public PlayerController[] players;
    public Transform[] spawnPoints;
    public float respawnTime;

    private int playersInGame;
    public GameObject FinishLine;

    //instance
    public static GameManager instance;

    void Awake ()
    {
        instance = this;
    } 

    void Start ()
    {
        players = new PlayerController[PhotonNetwork.PlayerList.Length];
        photonView.RPC("ImInGame", RpcTarget.AllBuffered);
    }

    [PunRPC]
    void Update ()
    {
        if(FinishLine == null)
            photonView.RPC("WinGame", RpcTarget.All, players.First(x => !x.dead).id);
    }

    [PunRPC]
    void ImInGame ()
    {
        playersInGame++;

        if(playersInGame == PhotonNetwork.PlayerList.Length)
            SpawnPlayer();
    }

    void SpawnPlayer ()
    {
        GameObject playerObj = PhotonNetwork.Instantiate(playerPrefabPath, spawnPoints[Random.Range(0, spawnPoints.Length)].position, Quaternion.identity);

        //Initialize Player
        playerObj.GetComponent<PhotonView>().RPC("Initialize", RpcTarget.All, PhotonNetwork.LocalPlayer);
    }

    public PlayerController GetPlayer (int playerId)
    {
        return players.First(x => x.id == playerId);
    }

    [PunRPC]
    public void WinGame (int winningPlayer)
    {
        //set UI Win Text
        GameUI.instance.SetWinText(GetPlayer(winningPlayer).photonPlayer.NickName);

        NetworkManager.instance.ChangeScene("Menu");
    }

    // void GoBackToMenu ()
    // {
        
    // }
}
